### ISSUE TITLE
Search method answers with switched album/artist parameters

### ISSUE THREAD

**Issue by teo** [eskerda/owncloud-submedia-app#18]
Example:
"id":108,
"parent":"album_26",
"title":"Star Guide",
"album":"try^d",              //should be artist
"artist":"Public Domain",  //should be album
"isDir":false,
"coverArt":"album_26",
"duration":186,
"bitRate":207,
"track":0,
"size":4812220,
"suffix":"mp3",
"contentType":"audio/mpeg",
"isVideo":false,
"path":"Public Domain/try^d/0 - Star Guide.mp3",
"albumId":"album_26",
"artistId":"artist_24",
"type":"music"

**Comment by eskerda** [comment]
Woops, thanks!

**Comment by teo** [comment]
Thanks for fixing!

**Comment by eskerda** [comment]
Is it urgent? We can release a hotfix on the development server, or just wait for the next update.

**Comment by teo** [comment]
Well, I cannot do Submedia-specific development until it's deployed, but other non Submedia-specific ScriptCollection tasks are not blocked because I can test using the Ampache resolver, which is the only other one that supports ScriptCollections. I'm fixing such a bug now, which is not Submedia-specific but still affects the Subsonic/Submedia resolver.
This is to say: I'd appreciate if your fix was deployed ASAP, but if that's too much of a hassle I'll find other stuff to fix while I wait.

**Comment by eskerda** [comment]
No problem! The hotfix is out and will get merged as soon as possible.

**Comment by teo** [comment]
Awesome! Many thanks!
