### ISSUE TITLE
Wrong track number and path on non-mp3 files

### ISSUE THREAD

**Issue by teo** [eskerda/owncloud-submedia-app#19]
When a track is searched or otherwise requested that happens to be stored on ownCloud as an Ogg file (or possibly other formats), Submedia always reports the "track" metadata field as "0".
It and also reports the contentType as audio/mpeg and gives a filename like "0 - song name.mp3" rather than the real name. This is no big problem because we stream tracks by id rather than by path, but it's still incorrect.
According to (1) (see "child" elements, it's the same for other API calls), contentType should always reflect the original format, with other parameters indicating transcoding, if any. I don't think we need transcoding at this point, but we do need correct metadata for non-mp3 files.

[1] http://subsonic.svn.sourceforge.net/viewvc/subsonic/trunk/subsonic-main/src/main/webapp/xsd/indexes_example_1.xml?annotate=2853

**Comment by eskerda** [comment]
- **track number**, the thing is that's what OwnCloud is reporting. So, there's no default way of knowing if one song track is 0 or is an error. We could only assume all ogg files have a wrong 0 track, and decide to not show it.
- **Content type**. I do agree, however, we have to guess it by the filename. That's what is stored on the database. We could, for instance, do a direct access to files. But there's an OwnCloud moment to do that (when files are scanned for media). I don't think it's a good idea to do file access when listing on the API. So, the only thing left is fixing OwnCloud's metadata reading for ogg files, or we can always just guess it by filename. We could even do both things, as owncloud does not store the content type of media files into the database.

**Comment by teo** [comment]
Not showing the track number is not very different from showing all zeros really, either way the tracks in an album cannot be sorted correctly.
Also I think we should avoid guessing from filenames if possible. For example, an .ogg container can have lots of different kinds of streams inside it, including FLAC, Vorbis, etc. Guessing from filenames would be quite unreliable for this purpose. But either way I think track numbers are more important than content type at this point.

**Comment by eskerda** [comment]
What I meant is that from a pragmatic point of view (as an app) we do not have any other way different than guessing to know if a file is ogg, or even that the track number is wrong, as it is stored as 0 in the database.

**Comment by eskerda** [comment]
Oh, my bad. ownCloud does in fact handle ogg metadata correctly. The problem is that vorbis comments use the key 'track_number', and the file scanning function in owncloud is just looking for 'track' and 'tracknumber'.

The real problem, though, is that the sql schema has a not null constrict in the track number column. So, when no track is available, it is set to 0.

**Comment by eskerda** [comment]
Added a pull request on https://github.com/owncloud/apps/pull/671
